### ISSUE TITLE
Cool T-Shirt Project Summary & Rubric Score

### ISSUE THREAD

**Issue by karl-project-review** [Kim-marketing-io/sql-scratch-capstone-turn-in#1]
### Criteria 1: Report: Are conclusions clear and supported by evidence in all eight answers?
* _Score Level:_ 4/4 (Exceeds Expectations)
* _Comment(s):_ All of your conclusions are clearly stated, well-reasoned, and supported by the results of your included queries. Well done!
### Criteria 2: Query Accuracy: Do queries do what they were supposed to do?
* _Score Level:_ 4/4 (Meets Expectations)
* _Comment(s):_ Your queries perform as advertised. Nice work!
### Criteria 3: Query Formatting
* _Score Level:_ 3/4 (Meets Expectations)
* _Comment(s):_ Your SQL code adheres to most of the formatting guidelines. However, DISTINCT, COUNT, DESC, and AS are all reserved keywords that should be consistently capitalized (for example, in lines 5, 9, 13, 19, 22, 26, 27, 31, etc of the sql_code.sql file). Also, the formatting guidelines recommend using numbers when referring to aggregate or calculated values in GROUP BYs and ORDER BYs (for example, in lines 31, 47, etc). Also, while you do a good job of splitting up columns being selected onto their own lines, we recommend putting the alias on the same line as its corresponding column name. 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 4/4 (Exceeds Expectations)
* _Comment(s):_ This report demonstrates a clear understanding of touch attribution, UTM parameters, and funnels as well. Good job!

### Overall Score: 15/16 (Meets Expectations)
Nice work on this project! Your SQL queries do what they are supposed to, and you provided reasonable interpretations of the results of those queries. My main recommendation for you is to focus on consistently adhering to the formatting guidelines, as this will make your code easy to follow and understand when working on longer, more complex projects. And with regards to your question at the end of your report on why that query didn't seem to be working yet wasn't displaying any error message, I believe it is working just fine, it just isn't returning any rows because no one's first touch was on the purchase page. Thus, there are no results to display. Again, well done!

**Comment by Kim-marketing-io** [comment]
Great! thanks a lot Karl  💃 :D
